In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("anotherMessySet.csv")

In [3]:
print
df

,ID,Name,Surname,Age,Email,Salary (R),Joining Date,Department,Phone Number,Manager
0,40,Eva,Smith,23.0,eva@ex.co,65000,2023-02-10,HR,+27 60 123 4567,Sarah Johnson
1,26,Alicia,Mdlamini,31.0,alicia@example.com,"50,000",2022-01-15,HR,061-234-5678,Sarah Johnson
2,27,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,+27623456789,Michael Brown
3,4,David,Mokoena,22.0,david@example.com,50000,2021-07-10,Finance,0634567890,Emily Davis
4,36,Alicia,Mdlamini,26.0,alicia@example.com,"50,000",2022-01-15,HR,+27(64)567-8901,Sarah Johnson
5,2,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,+2765-678-9012,Michael Brown
6,5,Eva,Smith,27.0,eva@ex.co,65000,2023-02-10,HR,066 789 0123,Sarah Johnson
7,13,Charles,Nkosi,NaN,charles@example.com,60000,2020-03-03,Marketing,+27 67 890 1234,Laura Smith
8,9,David,Mokoena,23.0,david@example.com,50000,2021-07-10,Finance,+27-68-901-2345,Emily Davis
9,4,David,Mokoena,22.0,david@example.com,50000,2021-07-10,Finance,69 012 3456,Emily Davis
10,7,Robert,NaN,29.0,robert@example.com,55000,2021-02-15,Engineering,070 123 4567,Michael Brown
11,25,Eva,Smith,23.0,eva@ex.co,65000,2023-02-10,HR,071 234 5678,Sarah Johnson
12,33,Charles,Nkosi,22.0,charles@example.com,60000,2020-03-03,Marketing,+2772 345 6789,Laura Smith
13,20,Eva,NaN,25.0,eva@ex.co,65000,2023-02-10,HR,+2773-456-7890,Sarah Johnson
14,18,Charles,Nkosi,22.0,charles@example.com,60000,2020-03-03,Marketing,074 567 8901,Laura Smith
15,14,David,Mokoena,21.0,david@example.com,50000,2021-07-10,Finance,+27-75-678-9012,Emily Davis
16,3,Charles,Nkosi,30.0,charles@example.com,60000,2020-03-03,Marketing,076 789 0123,Laura Smith
17,16,Alicia,Mdlamini,27.0,alicia@example.com,"50,000",2022-01-15,HR,+2777 890 1234,Sarah Johnson
18,10,Eva,Smith,31.0,eva@ex.co,65000,2023-02-10,HR,+27 78 901 2345,Sarah Johnson
19,17,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,079 012 3456,Michael Brown
20,38,Charles,Nkosi,29.0,charles@example.com,60000,2020-03-03,Marketing,080 123 4567,Laura Smith
21,32,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,081 234 5678,Michael Brown
22,28,Charles,Nkosi,28.0,charles@example.com,60000,2020-03-03,Marketing,082-345-6789,Laura Smith
23,1,Alicia,Mdlamini,25.0,alicia@example.com,"50,000",2022-01-15,HR,+27 (83) 456-7890,Sarah Johnson
24,31,Alicia,NaN,27.0,alicia@example.com,"50,000",2022-01-15,HR,084 567 8901,Sarah Johnson
25,30,Eva,Smith,21.0,eva@ex.co,65000,2023-02-10,HR,0856789012,Sarah Johnson
26,6,Alicia,Mdlamini,26.0,alicia@example.com,"50,000",2022-01-15,HR,086-789-0123,Sarah Johnson
27,12,Robert,NaN,28.0,robert@example.com,55000,2021-02-15,Engineering,087 890 1234,Michael Brown
28,34,David,Mokoena,30.0,david@example.com,50000,2021-07-10,Finance,+2788 901 2345,Emily Davis
29,2,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,+27 (89) 012-3456,Michael Brown
30,1,Alicia,Mdlamini,25.0,alicia@example.com,"50,000",2022-01-15,HR,090-123-4567,Sarah Johnson
31,22,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,091-234-5678,Michael Brown
32,3,Charles,Nkosi,30.0,charles@example.com,60000,2020-03-03,Marketing,+27(92)345-6789,Laura Smith
33,35,Eva,NaN,25.0,eva@ex.co,65000,2023-02-10,HR,+27 93 456 7890,Sarah Johnson
34,24,David,NaN,david@example.com,50000,2021-07-10,Finance,+27-94-567-8901,Emily Davis,NaN
35,37,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,095 678 9012,Michael Brown
36,11,Alicia,Mdlamini,24.0,alicia@example.com,"50,000",2022-01-15,HR,+27 (96) 789-0123,Sarah Johnson
37,23,Charles,Nkosi,29.0,charles@example.com,60000,2020-03-03,Marketing,097 890 1234,Laura Smith
38,19,David,Mokoena,30.0,david@example.com,50000,2021-07-10,Finance,098-901-2345,Emily Davis
39,5,Eva,Smith,27.0,eva@ex.co,65000,2023-02-10,HR,099 012 3456,Sarah Johnson
40,21,Alicia,NaN,26.0,alicia@example.com,"50,000",2022-01-15,HR,060-123-4567,Sarah Johnson
41,8,Charles,Nkosi,NaN,charles@example.com,60000,2020-03-03,Marketing,+27-61-234-5678,Laura Smith
42,15,Eva,Smith,26.0,eva@ex.co,65000,2023-02-10,HR,062-345-6789,Sarah Johnson
43,29,David,Mokoena,NaN,david@example.com,50000,2021-07-10,Finance,063 456 7890,Emily Davis
44,39,David,NaN,david@example.com,50000,2021-07-10,Finance,064-567-8901,Emily Davis,NaN

In [4]:
df.drop_duplicates()

,ID,Name,Surname,Age,Email,Salary (R),Joining Date,Department,Phone Number,Manager
0,40,Eva,Smith,23.0,eva@ex.co,65000,2023-02-10,HR,+27 60 123 4567,Sarah Johnson
1,26,Alicia,Mdlamini,31.0,alicia@example.com,"50,000",2022-01-15,HR,061-234-5678,Sarah Johnson
2,27,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,+27623456789,Michael Brown
3,4,David,Mokoena,22.0,david@example.com,50000,2021-07-10,Finance,0634567890,Emily Davis
4,36,Alicia,Mdlamini,26.0,alicia@example.com,"50,000",2022-01-15,HR,+27(64)567-8901,Sarah Johnson
5,2,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,+2765-678-9012,Michael Brown
6,5,Eva,Smith,27.0,eva@ex.co,65000,2023-02-10,HR,066 789 0123,Sarah Johnson
7,13,Charles,Nkosi,NaN,charles@example.com,60000,2020-03-03,Marketing,+27 67 890 1234,Laura Smith
8,9,David,Mokoena,23.0,david@example.com,50000,2021-07-10,Finance,+27-68-901-2345,Emily Davis
9,4,David,Mokoena,22.0,david@example.com,50000,2021-07-10,Finance,69 012 3456,Emily Davis
10,7,Robert,NaN,29.0,robert@example.com,55000,2021-02-15,Engineering,070 123 4567,Michael Brown
11,25,Eva,Smith,23.0,eva@ex.co,65000,2023-02-10,HR,071 234 5678,Sarah Johnson
12,33,Charles,Nkosi,22.0,charles@example.com,60000,2020-03-03,Marketing,+2772 345 6789,Laura Smith
13,20,Eva,NaN,25.0,eva@ex.co,65000,2023-02-10,HR,+2773-456-7890,Sarah Johnson
14,18,Charles,Nkosi,22.0,charles@example.com,60000,2020-03-03,Marketing,074 567 8901,Laura Smith
15,14,David,Mokoena,21.0,david@example.com,50000,2021-07-10,Finance,+27-75-678-9012,Emily Davis
16,3,Charles,Nkosi,30.0,charles@example.com,60000,2020-03-03,Marketing,076 789 0123,Laura Smith
17,16,Alicia,Mdlamini,27.0,alicia@example.com,"50,000",2022-01-15,HR,+2777 890 1234,Sarah Johnson
18,10,Eva,Smith,31.0,eva@ex.co,65000,2023-02-10,HR,+27 78 901 2345,Sarah Johnson
19,17,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,079 012 3456,Michael Brown
20,38,Charles,Nkosi,29.0,charles@example.com,60000,2020-03-03,Marketing,080 123 4567,Laura Smith
21,32,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,081 234 5678,Michael Brown
22,28,Charles,Nkosi,28.0,charles@example.com,60000,2020-03-03,Marketing,082-345-6789,Laura Smith
23,1,Alicia,Mdlamini,25.0,alicia@example.com,"50,000",2022-01-15,HR,+27 (83) 456-7890,Sarah Johnson
24,31,Alicia,NaN,27.0,alicia@example.com,"50,000",2022-01-15,HR,084 567 8901,Sarah Johnson
25,30,Eva,Smith,21.0,eva@ex.co,65000,2023-02-10,HR,0856789012,Sarah Johnson
26,6,Alicia,Mdlamini,26.0,alicia@example.com,"50,000",2022-01-15,HR,086-789-0123,Sarah Johnson
27,12,Robert,NaN,28.0,robert@example.com,55000,2021-02-15,Engineering,087 890 1234,Michael Brown
28,34,David,Mokoena,30.0,david@example.com,50000,2021-07-10,Finance,+2788 901 2345,Emily Davis
29,2,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,+27 (89) 012-3456,Michael Brown
30,1,Alicia,Mdlamini,25.0,alicia@example.com,"50,000",2022-01-15,HR,090-123-4567,Sarah Johnson
31,22,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,091-234-5678,Michael Brown
32,3,Charles,Nkosi,30.0,charles@example.com,60000,2020-03-03,Marketing,+27(92)345-6789,Laura Smith
33,35,Eva,NaN,25.0,eva@ex.co,65000,2023-02-10,HR,+27 93 456 7890,Sarah Johnson
34,24,David,NaN,david@example.com,50000,2021-07-10,Finance,+27-94-567-8901,Emily Davis,NaN
35,37,Robert,NaN,24.0,robert@example.com,55000,2021-02-15,Engineering,095 678 9012,Michael Brown
36,11,Alicia,Mdlamini,24.0,alicia@example.com,"50,000",2022-01-15,HR,+27 (96) 789-0123,Sarah Johnson
37,23,Charles,Nkosi,29.0,charles@example.com,60000,2020-03-03,Marketing,097 890 1234,Laura Smith
38,19,David,Mokoena,30.0,david@example.com,50000,2021-07-10,Finance,098-901-2345,Emily Davis
39,5,Eva,Smith,27.0,eva@ex.co,65000,2023-02-10,HR,099 012 3456,Sarah Johnson
40,21,Alicia,NaN,26.0,alicia@example.com,"50,000",2022-01-15,HR,060-123-4567,Sarah Johnson
41,8,Charles,Nkosi,NaN,charles@example.com,60000,2020-03-03,Marketing,+27-61-234-5678,Laura Smith
42,15,Eva,Smith,26.0,eva@ex.co,65000,2023-02-10,HR,062-345-6789,Sarah Johnson
43,29,David,Mokoena,NaN,david@example.com,50000,2021-07-10,Finance,063 456 7890,Emily Davis
44,39,David,NaN,david@example.com,50000,2021-07-10,Finance,064-567-8901,Emily Davis,NaN

In [5]:
df= pd.read_csv("anotherMessyset.csv")
df.dropna(inplace =True)
print(df.to_string())

    ID     Name   Surname   Age                Email Salary (R) Joining Date Department       Phone Number        Manager
0   40      Eva     Smith  23.0            eva@ex.co      65000   2023-02-10         HR    +27 60 123 4567  Sarah Johnson
1   26   Alicia  Mdlamini  31.0   alicia@example.com     50,000   2022-01-15         HR       061-234-5678  Sarah Johnson
3    4    David   Mokoena  22.0    david@example.com      50000   2021-07-10    Finance         0634567890    Emily Davis
4   36   Alicia  Mdlamini  26.0   alicia@example.com     50,000   2022-01-15         HR    +27(64)567-8901  Sarah Johnson
6    5      Eva     Smith  27.0            eva@ex.co      65000   2023-02-10         HR       066 789 0123  Sarah Johnson
8    9    David   Mokoena  23.0    david@example.com      50000   2021-07-10    Finance    +27-68-901-2345    Emily Davis
9    4    David   Mokoena  22.0    david@example.com      50000   2021-07-10    Finance        69 012 3456    Emily Davis
11  25      Eva     Smith  23.0            eva@ex.co      65000   2023-02-10         HR       071 234 5678  Sarah Johnson
12  33  Charles     Nkosi  22.0  charles@example.com      60000   2020-03-03  Marketing     +2772 345 6789    Laura Smith
14  18  Charles     Nkosi  22.0  charles@example.com      60000   2020-03-03  Marketing       074 567 8901    Laura Smith
15  14    David   Mokoena  21.0    david@example.com      50000   2021-07-10    Finance    +27-75-678-9012    Emily Davis
16   3  Charles     Nkosi  30.0  charles@example.com      60000   2020-03-03  Marketing       076 789 0123    Laura Smith
17  16   Alicia  Mdlamini  27.0   alicia@example.com     50,000   2022-01-15         HR     +2777 890 1234  Sarah Johnson
18  10      Eva     Smith  31.0            eva@ex.co      65000   2023-02-10         HR    +27 78 901 2345  Sarah Johnson
20  38  Charles     Nkosi  29.0  charles@example.com      60000   2020-03-03  Marketing       080 123 4567    Laura Smith
22  28  Charles     Nkosi  28.0  charles@example.com      60000   2020-03-03  Marketing       082-345-6789    Laura Smith
23   1   Alicia  Mdlamini  25.0   alicia@example.com     50,000   2022-01-15         HR  +27 (83) 456-7890  Sarah Johnson
25  30      Eva     Smith  21.0            eva@ex.co      65000   2023-02-10         HR         0856789012  Sarah Johnson
26   6   Alicia  Mdlamini  26.0   alicia@example.com     50,000   2022-01-15         HR       086-789-0123  Sarah Johnson
28  34    David   Mokoena  30.0    david@example.com      50000   2021-07-10    Finance     +2788 901 2345    Emily Davis
30   1   Alicia  Mdlamini  25.0   alicia@example.com     50,000   2022-01-15         HR       090-123-4567  Sarah Johnson
32   3  Charles     Nkosi  30.0  charles@example.com      60000   2020-03-03  Marketing    +27(92)345-6789    Laura Smith
36  11   Alicia  Mdlamini  24.0   alicia@example.com     50,000   2022-01-15         HR  +27 (96) 789-0123  Sarah Johnson
37  23  Charles     Nkosi  29.0  charles@example.com      60000   2020-03-03  Marketing       097 890 1234    Laura Smith
38  19    David   Mokoena  30.0    david@example.com      50000   2021-07-10    Finance       098-901-2345    Emily Davis
39   5      Eva     Smith  27.0            eva@ex.co      65000   2023-02-10         HR       099 012 3456  Sarah Johnson
42  15      Eva     Smith  26.0            eva@ex.co      65000   2023-02-10         HR       062-345-6789  Sarah Johnson

In [6]:
df = df.dropna()
df['Name'] = df['Name'].drop_duplicates()
df = df.dropna()
df

,ID,Name,Surname,Age,Email,Salary (R),Joining Date,Department,Phone Number,Manager
0,40,Eva,Smith,23.0,eva@ex.co,65000,2023-02-10,HR,+27 60 123 4567,Sarah Johnson
1,26,Alicia,Mdlamini,31.0,alicia@example.com,"50,000",2022-01-15,HR,061-234-5678,Sarah Johnson
3,4,David,Mokoena,22.0,david@example.com,50000,2021-07-10,Finance,0634567890,Emily Davis
12,33,Charles,Nkosi,22.0,charles@example.com,60000,2020-03-03,Marketing,+2772 345 6789,Laura Smith

In [11]:
df['Joining Date'] = df['Joining Date'].str.replace('-','' )
df.at[0, 'Joining Date'] = df.at[0, 'Joining Date'].replace('/', '')

df.at[0, 'Joining Date'] = pd.to_datetime(df.at[0, 'Joining Date'], format='%Y%m%d').strftime('%d-%m-%Y')
df.at[1, 'Joining Date'] = pd.to_datetime(df.at[1, 'Joining Date'], format='%Y%m%d').strftime('%d-%m-%Y')

df.at[3, 'Joining Date'] = pd.to_datetime(df.at[3, 'Joining Date'], format='%Y%m%d').strftime('%d-%m-%Y')
df.at[12, 'Joining Date'] = pd.to_datetime(df.at[12, 'Joining Date'], format='%Y%m%d').strftime('%d-%m-%Y')

In [12]:
df

,ID,Name,Surname,Age,Email,Salary (R),Joining Date,Department,Phone Number,Manager
0,40,Eva,Smith,23.0,eva@ex.co,65000,10-02-2023,HR,+27 60 123 4567,Sarah Johnson
1,26,Alicia,Mdlamini,31.0,alicia@example.com,"50,000",15-01-2022,HR,061-234-5678,Sarah Johnson
3,4,David,Mokoena,22.0,david@example.com,50000,10-07-2021,Finance,0634567890,Emily Davis
12,33,Charles,Nkosi,22.0,charles@example.com,60000,03-03-2020,Marketing,+2772 345 6789,Laura Smith